name: admin_app
description: A new Flutter project.

publish_to: "none"
version: 1.1.9+91

environment:
  sdk: ">=2.18.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  data_table_2:
  syncfusion_flutter_charts: ^33.2.12
  dio: ^4.0.6
  provider:
  shared_preferences: 2.2.3
  group_radio_button:
  http:
  flutter_redux: ^0.10.0
  intl: ^0.20.2
  contained_tab_bar_view:
  pin_code_fields: ^9.4.0
  flutter_easyloading:
  lottie:
  multi_select_flutter:
  pdf:
  syncfusion_flutter_pdf:
  path_provider:
  open_filex:
  permission_handler:
  flutter_polyline_points:
  google_maps_flutter: ^2.17.1
  location:
  geocoding:
  flutter_secure_storage:
  get:
  google_maps_cluster_manager: ^3.1.0
#  flutter_local_notifications:
  path:
  webview_flutter:
  flutter_svg:
  sizer:
  device_preview: ^1.3.1
  auto_size_text: ^3.0.0
  dropdown_search:
  search_choices:
  modal_bottom_sheet:
  wakelock_plus: ^1.2.8
  custom_info_window: ^1.0.1
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - images/
    - images/caricon-icondred.png
    - images/caricon-greenicon.png
    - images/caricongreen.png
    - images/cariconwhite.png
    - images/bus-red.png
    - images/caricongrey.png
    - images/cariconred.png
    - images/adminimage5.png
    - images/adminimage6.png
    - images/adminimage3.png
    - images/adminimage2.png
    - images/person.jpg
    - images/caricon.png
    - images/logo.png
    - images/map.png
    - images/person-icon.png
    - images/forgotpasswordimage.png
    - images/arrow.png
    - images/profile.jpg
    - images/truckicon.png
    - images/caricon-grayicon.png
    - images/busicon.png
    - images/65095-car-animation.json
    - images/caricontransparent.png
    - images/busicontransparent.png
    - images/truckicontransparent.png
    - images/addtrip.jpg
    - images/tripimage.jpeg
    - images/bus-green.png
    - images/truckred.png
    - images/truckgreen.png
    - images/new-car-icon-red.png
    - images/new-car-icon-green.png
    - images/
    - images/car-top-view.png
    - images/vehiclecar.svg
    - images/location.png
    - images/location_map.png
    - images/navigation-marker.png
    - images/deadline.png
#    - Fonts/arial.ttf

#  fonts:
#    - family: Arial
#      fonts:
#        - asset: Fonts/arial.ttf